Vagrant.configure("2") do |config|
  # Configuration for the first Docker container
  config.vm.provider :docker do |d|
    d.build_dir = "./docker-test/"
    d.remains_running = true
    d.has_ssh = true
  end

  # Configuration for the second Docker container
  config.vm.define "admin" do |admin|
    admin.vm.provider :docker do |d|
    admin.vm.network "private_network", ip: "10.9.8.5"
      d.remains_running = true
      d.has_ssh = true
      d.name = "admin" # Setting a custom name for the container
    end
  end

  # Configuration for the third Docker container
  config.vm.define "server02" do |server01|
    server01.vm.provider :docker do |d|
    server01.vm.network "private_network", ip: "10.9.8.6"
      d.remains_running = true
      d.has_ssh = true
      d.name = "server01" # Setting a custom name for the container
    end
  end

  # Configuration for the third Docker container
  config.vm.define "server02" do |test3|
    server02.vm.provider :docker do |d|
    server02.vm.network "private_network", ip: "10.9.8.9"
      d.remains_running = true
      d.has_ssh = true
      d.name = "server02" # Setting a custom name for the container
    end
  end
end
