Vagrant.configure("2") do |config|
  # Configuration for the first Docker container
  config.vm.provider :docker do |d|
    d.build_dir = "./docker-test/"
    d.remains_running = true
    d.has_ssh = true
  end

  # Configuration for the second Docker container
  config.vm.define "test1" do |test1|
    test1.vm.provider :docker do |d|
    test1.vm.network "private_network", ip: "10.9.8.5"
      d.remains_running = true
      d.has_ssh = true
      d.name = "test1" # Setting a custom name for the container
    end
  end

  # Configuration for the third Docker container
  config.vm.define "test2" do |test2|
    test2.vm.provider :docker do |d|
    test2.vm.network "private_network", ip: "10.9.8.6"
      d.remains_running = true
      d.has_ssh = true
      d.name = "test2" # Setting a custom name for the container
    end
  end

  # Configuration for the third Docker container
  config.vm.define "test3" do |test3|
    test3.vm.provider :docker do |d|
    test3.vm.network "private_network", ip: "10.9.8.9"
      d.remains_running = true
      d.has_ssh = true
      d.name = "test3" # Setting a custom name for the container
    end
  end
end
