Vagrant.configure("2") do |config|
    config.vm.provider :docker do |d|
        d.image = "my-centos-image"
        #    d.image = "."
        d.remains_running = true
        d.has_ssh = true
        config.vm.boot_timeout = 600  
        config.ssh.insert_key = false
       config.vm.provision "shell", inline: <<-SHELL
       sudo rm -f /etc/ssh/ssh_host_*
       sudo ssh-keygen -A
       sudo systemctl restart sshd
     SHELL
    end
end
